# -*- coding: utf-8 -*-
"""NLP lab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18hOrqclJlxIyXbvj387Y1AgR_DgZAzhG
"""

!pip install spacy stanza

import nltk
from nltk.corpus import wordnet as wn
from nltk.wsd import lesk
import spacy
nlp = spacy.load("en_core_web_sm")
def perform_srl(text):
    doc = nlp(text)
    srl_output = []
    for token in doc:
        if token.dep_ in ["nsubj", "dobj", "pobj"]:
            srl_output.append(f"{token.dep_}: {token.text}")
    return srl_output
def perform_wsd(sentence):
    words = nltk.word_tokenize(sentence)
    wsd_output = {}
    for word in words:
        synset = lesk(sentence, word)
        if synset:
            wsd_output[word] = synset.definition()
    return wsd_output
def generate_response(srl_result, wsd_result):
    response = "\n=== Semantic Role Labeling (SRL) ===\n"
    response += "\n".join(srl_result) if srl_result else "No roles identified."

    response += "\n\n=== Word Sense Disambiguation (WSD) ===\n"
    for word, meaning in wsd_result.items():
        response += f"{word} -> {meaning}\n"

    return response
print("Enter a 4-line dialogue:")
user_input = "\n".join([input(f"Line {i+1}: ") for i in range(4)])
srl_result = perform_srl(user_input)
wsd_result = perform_wsd(user_input)
bot_response = generate_response(srl_result, wsd_result)

print(bot_response)