# -*- coding: utf-8 -*-
"""nlp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVP6UFuuR5v5VG_scz1Te9tzVUTWrYN9
"""

import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import LancasterStemmer

!pip install nltk

nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

text = "The Runner is running in the field and he won the match and came in the first place."

def tokenize_text(text):
    words = word_tokenize(text)
    sentences = sent_tokenize(text)
    return words, sentences

words, sentences = tokenize_text(text)
print("Word Tokenization:", words)
print("Sentence Tokenization:", sentences)

def remove_stopwords(words):
    stop_words = set(stopwords.words('english'))
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return filtered_words

filtered_words = remove_stopwords(words)
print("Filtered Words (Stopwords Removed):", filtered_words)

def stem_words(words):
    stemmer = LancasterStemmer()
    stemmed_words = [stemmer.stem(word) for word in words]
    return stemmed_words

stemmed_words = stem_words(filtered_words)
print("Stemmed Words:", stemmed_words)