# -*- coding: utf-8 -*-
"""nlp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjYsuV9Cl-C30rGNpyJvdAN9P1L3GuDl
"""

import string
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

import nltk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

def clean_text(text):
   text = text.lower()
   text = re.sub(f"[{string.punctuation}]", "", text)
   text = re.sub(r"\d+", "", text)
   tokens = word_tokenize(text)
   stop_words = set(stopwords.words("english"))
   tokens = [word for word in tokens if word not in stop_words]
   stemmer = PorterStemmer()
   stemmed_tokens = [stemmer.stem(word) for word in tokens]
   lemmatizer = WordNetLemmatizer()
   lemmatized_tokens = [lemmatizer.lemmatize(word) for word in stemmed_tokens]
   return " ".join(lemmatized_tokens)

def tokenize_text(text):
    tokens = word_tokenize(text)
    sentences = sent_tokenize(text)
    return tokens, sentences

if __name__ == "__main__":
    print("Enter the text you want to process:")
    user_input = input()
    tokens, sentences = tokenize_text(user_input)
    print("\nTokens:")
    print(tokens)
    print("\nSentences:")
    print(sentences)
    processed_text = clean_text(user_input)
    print("\nProcessed Text:")
    print(processed_text)

